name: Main Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/workflows/actions/setup-environment

      - name: Run unit tests
        run: pnpm test:unit

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/workflows/actions/setup-environment

      - name: Run type check
        run: pnpm type-check

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [unit-tests, type-check]
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/workflows/actions/setup-environment

      - name: Build for production
        run: pnpm build
