name: Pull Request Checks

on:
  pull_request:
    branches: [develop, master]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/workflows/actions/setup-environment

      - name: Run type check
        run: pnpm type-check

  unit-tests:
    name: Unit Tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/workflows/actions/setup-environment

      - name: Run unit tests
        run: pnpm test:unit

  e2e-tests:
    name: E2E Tests
    needs: lint
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/workflows/actions/setup-environment

      - name: Install Playwright browsers
        run: pnpm exec playwright install chromium

      - name: Build application
        run: pnpm build

      - name: Run E2E tests
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          E2E_USERNAME_ID: ${{ secrets.E2E_USERNAME_ID }}
          E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
          E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
        run: pnpm start & pnpm test:e2e

  status-comment:
    name: Update PR Status
    needs: [unit-tests, e2e-tests]
    runs-on: ubuntu-latest
    if: always()
    permissions:
      pull-requests: write
    steps:
      - name: Create Status Comment
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          script: |
            const unitTests = '${{ needs.unit-tests.result }}';
            const e2eTests = '${{ needs.e2e-tests.result }}';
            const allPassed = unitTests === 'success' && e2eTests === 'success';

            const statusEmoji = allPassed ? '✅' : '❌';
            const statusText = allPassed ? 'All checks passed!' : 'Some checks failed.';

            const comment = `## Pull Request Status ${statusEmoji}\n\n` +
              `${statusText}\n\n` +
              `- Unit Tests: ${unitTests === 'success' ? '✅' : '❌'}\n` +
              `- E2E Tests: ${e2eTests === 'success' ? '✅' : '❌'}\n\n`

            if (process.env.PR_NUMBER) {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: parseInt(process.env.PR_NUMBER),
                body: comment
              });
            }
